# Generated by Django 4.2.8 on 2024-07-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='package_expire_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
