# Generated by Django 4.2.8 on 2024-10-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='packageorder',
            name='package',
        ),
        migrations.RemoveField(
            model_name='packageorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='packageorder',
            name='store',
        ),
        migrations.RemoveField(
            model_name='store',
            name='package',
        ),
        migrations.RemoveField(
            model_name='store',
            name='package_expire_date',
        ),
        migrations.AddField(
            model_name='tag',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PackageOrder',
        ),
    ]
