# Generated by Django 4.2.8 on 2024-07-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_store_package_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='package_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
