# Generated by Django 4.2.8 on 2024-07-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='package_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
