# Generated by Django 4.2.8 on 2024-07-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_store_package_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='index_title',
            field=models.CharField(blank=True, default='خانه', max_length=250, null=True),
        ),
    ]
