# Generated by Django 4.2.8 on 2024-07-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_store_index_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='enamad_code',
            field=models.CharField(blank=True, default='none', max_length=1000, null=True),
        ),
    ]
