# Generated by Django 4.2.8 on 2024-07-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_store_enamad_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='body',
            field=models.TextField(),
        ),
    ]
