# Generated by Django 4.2.8 on 2024-07-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_ticket_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='has_payment_gw',
            field=models.BooleanField(default=False),
        ),
    ]
