# Generated by Django 4.2.8 on 2024-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_store_has_payment_gw'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='domain_msg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='gw_msg',
            field=models.BooleanField(default=False),
        ),
    ]
