# Generated by Django 4.2.8 on 2024-07-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
