# Generated by Django 4.2.15 on 2024-11-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_age_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='express',
            field=models.BooleanField(default=False),
        ),
    ]
