# Generated by Django 4.2.8 on 2024-07-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_announcement_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='has_notif',
            field=models.BooleanField(default=False),
        ),
    ]
