# Generated by Django 4.2.8 on 2024-08-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productrefclass_alter_product_ref_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ref_class',
        ),
    ]
