# Generated by Django 4.2.15 on 2024-12-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_expressdeliveryinterval_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='store',
        ),
    ]
