# Generated by Django 4.2.8 on 2024-08-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_ref_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ref_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productrefclass'),
        ),
    ]
