# Generated by Django 4.2.15 on 2024-12-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_productimage_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='store',
        ),
    ]
