# Generated by Django 4.2.8 on 2024-08-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_ref_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallet_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
