# Generated by Django 4.2.15 on 2024-12-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_order_delivery_cost_order_delivery_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='store',
        ),
        migrations.AddField(
            model_name='delivery',
            name='min_cart_free',
            field=models.IntegerField(default=2000000),
        ),
    ]
