# Generated by Django 4.2.8 on 2024-08-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_order_paid_by_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetation', models.IntegerField(default=0)),
                ('percent', models.IntegerField(default=0)),
                ('const', models.IntegerField(default=0)),
            ],
        ),
    ]
