# Generated by Django 4.2.8 on 2024-12-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_delivery_options_remove_delivery_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='min_cart_free_active',
            field=models.BooleanField(default=False),
        ),
    ]
