# Generated by Django 4.2.8 on 2024-12-11 13:43

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_delivery_min_cart_free_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default='media/11.png', upload_to=shop.models.brand_upload_path),
        ),
    ]
