# Generated by Django 4.2.8 on 2024-12-11 16:18

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.brand_upload_path),
        ),
    ]
