# Generated by Django 4.2.8 on 2024-12-15 10:18

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='store',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_cart_volume',
            field=models.IntegerField(default=0, verbose_name='حداقل مبلغ سبد خرید (تومان)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد کوپن'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='میزان تخفیف (تومان)'),
        ),
    ]
