# Generated by Django 4.2.8 on 2025-01-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_coupon_store_remove_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='media/11.png', upload_to='shahrtoy/products/'),
        ),
    ]
